### ISSUE TITLE
Contact me

### ISSUE THREAD

**Issue by freak-head** [naveenland4/Utube-Live#1]
Can you plz contact me on telegram
https://t.me/Reaper_OX

**Comment by naveenland4** [comment]
> Can you plz contact me on telegram https://t.me/Reaper_OX

Any issue bro?

**Comment by freak-head** [comment]
> > Can you plz contact me on telegram https://t.me/Reaper_OX
> 
> Any issue bro?

Not an actual issue but nammaoorutv repository really helped me a lot can u put that on public plz? Or make a private gist and share the private raw link without raw id in my telegram.

**Comment by naveenland4** [comment]
> > > Can you plz contact me on telegram https://t.me/Reaper_OX
> > 
> > 
> > Any issue bro?
> 
> Not an actual issue but nammaoorutv repository really helped me a lot can u put that on public plz? Or make a private gist and share the private raw link without raw id in my telegram.

Due to T20 World Cup Links i got pissed of due to Copyright issue. Thus it has been removed by Github.

**Comment by freak-head** [comment]
> > > > Can you plz contact me on telegram https://t.me/Reaper_OX
> > > 
> > > 
> > > Any issue bro?
> > 
> > 
> > Not an actual issue but nammaoorutv repository really helped me a lot can u put that on public plz? Or make a private gist and share the private raw link without raw id in my telegram.
> 
> Due to T20 World Cup Links i got pissed of due to Copyright issue. Thus it has been removed by Github.

Oh shit! How can i contact u bro? I want to tell u about this!
